# Generated by Django 4.1.7 on 2023-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_courses',
            field=models.ManyToManyField(blank=True, related_name='users_favorited', to='api.course'),
        ),
    ]
